### ISSUE TITLE
[Bug]: url domain.com/themes not work if PanelServiceProvider use ->path('admin')

### ISSUE THREAD

**Issue by jouniikaheimo** [Hasnayeen/themes#1]
### What happened?

multiple panelProvider example admin / tenant 
If there are multiple panels that use ->path('something') can't use domain.com/themes correct url is domain.com/something/themes.

i solve issue modify 

SetTheme.php 
```


 MenuItem::make('Themes')
                    ->label('Themes')
                    ->icon('heroicon-o-swatch')
                    ->url('/'.$panel->getPath().'/themes'),
            ] : []
```

### How to reproduce the bug

After installation 

i have TenantPanelServiceProvider.php where i use ->path('tenant')
and i have AdminPanelServiceProvider.php where i use ->path('admin')

### Package Version

lasted

### PHP Version

8.2.0

### Laravel Version

lasted

**Comment by Hasnayeen** [comment]
Thanks for submitting the bug report, a fix has been deployed 57f1eb27e94b574d4933cac43187d04e8cf1c334
