### ISSUE TITLE
[Bug]: Call to undefined method Filament\Support\Colors\Color::all()

### ISSUE THREAD

**Issue by ayzerobug** [Hasnayeen/themes#13]
### What happened?

Throws the expection at  Hasnayeen\Themes\Themes\DefaultTheme line 23.

### How to reproduce the bug

*

### Package Version

3.0.0

### PHP Version

8.1

### Laravel Version

10.8

**Comment by Hasnayeen** [comment]
@ayzerobug please mention exact filament & themes package version, you can get them via running `php artisan about` in terminal

**Comment by ayzerobug** [comment]
Themes:  default, dracula, nord, sunset
  Version: v3.0.14
  Filament Version: 3.0

**Comment by Hasnayeen** [comment]
> Themes: default, dracula, nord, sunset Version: v3.0.14 Filament Version: 3.0

upgrade filament to the latest version

**Comment by Rajesh-Dehury** [comment]
Same Issue
  Filament ......................................................................................................................  
  Packages ...................................................................... filament, forms, notifications, support, tables  
  Version ................................................................................................................ v3.0.0  
  Views ........................................................................................................... NOT PUBLISHED  

  Themes ........................................................................................................................  
  Themes ......................................................................................... default, dracula, nord, sunset  
  Version ............................................................................................................... v3.0.17  

  Livewire ......................................................................................................................  
  Livewire ............................................................................................................... v3.0.2

**Comment by Hasnayeen** [comment]
@Rajesh-Dehury update to latest filament (v3.0.47) please

**Comment by Hasnayeen** [comment]
closing this as there is no update, feel free to reopen this if issue persists

**Comment by ramandaaridogh** [comment]
![image](https://github.com/Hasnayeen/themes/assets/16524467/052231b6-70be-4f28-aab5-6485698fe56d)

@Hasnayeen 
Same issue...

![image](https://github.com/Hasnayeen/themes/assets/16524467/db6eda9a-9d18-4f0e-8723-2556ba23f688)

**Comment by Hasnayeen** [comment]
@ramandaaridogh update to latest filament

**Comment by ramandaaridogh** [comment]
> @ramandaaridogh update to latest filament

Already did. But still...

**Comment by Hasnayeen** [comment]
@ramandaaridogh what's your filament exact version?
