### ISSUE TITLE
[Bug]: Call to undefined method Hasnayeen\Themes\Themes\Dracula::getPrimaryColor()

### ISSUE THREAD

**Issue by Cooltriks** [Hasnayeen/themes#15]
### What happened?

After Update composer  
themes 3.0.13 to 3.0.16

### How to reproduce the bug

when updated composer 
and applied new theme then

 Call to undefined method Hasnayeen\Themes\Themes\Dracula::getPrimaryColor()

### Package Version

3.0.16

### Filament Version

3.0

### PHP Version

8.1

### Laravel Version

10

### Notes

Call to undefined method Hasnayeen\Themes\Themes\Dracula::getPrimaryColor()

Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0

**Comment by Hasnayeen** [comment]
Fixed by 7e53b64
