### ISSUE TITLE
[Bug]: Call to a member function can() on null

### ISSUE THREAD

**Issue by stephenjude** [Hasnayeen/themes#19]
### What happened?

 When a Filament user logs out this method `canViewThemesPage(fn () => auth()->user()->is_admin)` returns a `Call to a member function can() on null` error due to the absence of authenticated user object.

### How to reproduce the bug

- Call the authorization check method `canViewThemesPage(fn () => auth()->user()->is_admin)`.
- Log out of your Filament dashboard. 

<img width="1371" alt="image" src="https://github.com/Hasnayeen/themes/assets/31182887/a113dd08-e8ab-4551-9d3e-0919a9adc059">

### Package Version

3.0

### Filament Version

3.0

### PHP Version

8.2

### Laravel Version

10

**Comment by Hasnayeen** [comment]
This is not a bug, this method runs user provided callback function so if user pass invalid code then there will be error. For example if someone pass non existent method to the `canViewThemesPage` then there will be error

```php
canViewThemesPage(fn () => non_existent_method())
```
