### ISSUE TITLE
[Bug]: Call to undefined method Filament\Support\Colors\Color::all()

### ISSUE THREAD

**Issue by waleedGRT** [Hasnayeen/themes#2]
### What happened?

After installing this plugin and registering it in the Filament AdminPanelProvider, I encountered the following error: "I received an error stating 'Call to undefined method Filament\Support\Colors\Color::all()'."

Also

Not working (Class "App\Providers\Filament\Hasnayeen\Themes\ThemesPlugin" not found)

```
 public function panel(Panel $panel): Panel
    {
        return $panel
            ->plugin(
                Hasnayeen\Themes\ThemesPlugin::make()
            );
    }
```
    
Working

```
use Hasnayeen\Themes\ThemesPlugin;

 public function panel(Panel $panel): Panel
    {
        return $panel
            ->plugin(
                ThemesPlugin::make()
            );
    }




```

### How to reproduce the bug

After registering the plugin in AdminPanelProvider, I encountered an error. By the way, I'm testing this on Docker.

### Package Version

3.0

### PHP Version

8.1

### Laravel Version

10.10

**Comment by waleedGRT** [comment]
On "themes:upgrade" i also got this error
```

php artisan themes:upgrade
>>

   BadMethodCallException 

  Method Hasnayeen\Themes\Commands\UpgradeCommand::copyAsset does not exist.

  at vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:112
    108▕      */
    109▕     public function __call($method, $parameters)
    110▕     {
    111▕         if (! static::hasMacro($method)) {
  ➜ 112▕             throw new BadMethodCallException(sprintf(
    113▕                 'Method %s::%s does not exist.', static::class, $method
    114▕             ));
    115▕         }
    116▕

  i   Bad Method Call: Did you mean Hasnayeen\Themes\Commands\UpgradeCommand::complete() ?

      +13 vendor frames

  14  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by Hasnayeen** [comment]
> On "themes:upgrade" i also got this error
> 
> ```
> 
> php artisan themes:upgrade
> >>
> 
>    BadMethodCallException 
> 
>   Method Hasnayeen\Themes\Commands\UpgradeCommand::copyAsset does not exist.
> 
>   at vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:112
>     108▕      */
>     109▕     public function __call($method, $parameters)
>     110▕     {
>     111▕         if (! static::hasMacro($method)) {
>   ➜ 112▕             throw new BadMethodCallException(sprintf(
>     113▕                 'Method %s::%s does not exist.', static::class, $method
>     114▕             ));
>     115▕         }
>     116▕
> 
>   i   Bad Method Call: Did you mean Hasnayeen\Themes\Commands\UpgradeCommand::complete() ?
> 
>       +13 vendor frames
> 
>   14  artisan:35
>       Illuminate\Foundation\Console\Kernel::handle()
> ```

A fix has been pushed for this

**Comment by Hasnayeen** [comment]
can you show me the exact filament version you're using?

![image](https://github.com/Hasnayeen/themes/assets/9433499/13ea1b4e-7df9-42af-a199-96726ff37e76)

**Comment by waleedGRT** [comment]
![image](https://github.com/Hasnayeen/themes/assets/55159721/8536536d-3f92-49ea-976f-89916367d685)

**Comment by Hasnayeen** [comment]
> ![image](https://user-images.githubusercontent.com/55159721/265268617-8536536d-3f92-49ea-976f-89916367d685.png)

run `php artisan about` in terminal and tell me the exact filament version please

**Comment by waleedGRT** [comment]
It's a version problem. I updated the package, and it is now working.

**Comment by khrnchn** [comment]
> It's a version problem. I updated the package, and it is now working.

hello, did you update filament or the theme plugin?

**Comment by khrnchn** [comment]
i still got the error despite updating the package to the latest version. in panel provider i have included these:

![image](https://github.com/Hasnayeen/themes/assets/71305935/399c2045-fa4b-4f3f-a2ce-83a3a18814dd)

this is my filament version:

![image](https://github.com/Hasnayeen/themes/assets/71305935/9cd385cf-1635-4cd0-8328-333ce3034fac)

**Comment by khrnchn** [comment]
nevermind, i solved it by upgrading my filament version. thanks!

**Comment by mohandtharsha** [comment]
> use Hasnayeen\Themes\ThemesPlugin;

can you please what is the solution
