### ISSUE TITLE
Error when I use the override option

### ISSUE THREAD

**Issue by gergo85** [Hasnayeen/themes#22]
### What happened?

Error message: Hasnayeen\Themes\Themes::make(): Return value must be of type Hasnayeen\Themes\Contracts\Theme, none returned

### How to reproduce the bug

Set the "override" option to "true".

### Package Version

latest

### Filament Version

3.0.62

### PHP Version

8.2.4

### Laravel Version

10.25.1

### Notes

I use this code:

```
ThemesPlugin::make()
    ->registerTheme(
        [
            MyTheme::getName() => MyTheme::class
        ],
        true,
    ),
```

**Comment by Hasnayeen** [comment]
Fixed by ac1ee2e
