### ISSUE TITLE
Panel Switch plugin [Bug]: 

### ISSUE THREAD

**Issue by dmb-220** [Hasnayeen/themes#24]
### What happened?

PanelSwitch::configureUsing(function (PanelSwitch $panelSwitch) {
			$panelSwitch->labels([
            'admin' => 'PAGRINDINIS',
            'maiseliai' => 'MAIŠELIAI',
			'pakuotes' => 'PAKUOTĖS',])
			->iconSize(16)
			->icons([
				'admin' => 'heroicon-o-square-2-stack',
				'pakuotes' => 'heroicon-o-cube',
				'maiseliai' => 'heroicon-o-shopping-bag',
			], $asImage = false)
			->modalHeading('Pasirinkti')
			->modalWidth('sm')
			//->slideOver();
			->simple();
		});
works with simple(), not works slideOver or Modal.
theme Nord, other theme all good

### How to reproduce the bug

no

### Package Version

3.0.67

### Filament Version

3.0.67

### PHP Version

8.1.5

### Laravel Version

10

**Comment by Hasnayeen** [comment]
bug is not occurring in the latest version, if it still does please reopen
