### ISSUE TITLE
[Bug]:  Call to undefined method Filament\Support\Colors\Color::all()

### ISSUE THREAD

**Issue by daab** [Hasnayeen/themes#27]
### What happened?

Method all() no exist in filament 3.0-stable

### How to reproduce the bug

Install and run

### Package Version

3.x

### Filament Version

3.x

### PHP Version

8.2

### Laravel Version

10.28.0

### Notes

Error

**Comment by Hasnayeen** [comment]
@daab upgrade to latest filament

**Comment by daab** [comment]
Filament\Support\Colors\Color; does not have the method all() 

    public function getThemeColor(): array
    {
        return Arr::except(Color::all(), ['gray', 'zinc', 'neutral', 'stone']);
    }

I upgraded to the latest version of Filament.

**Comment by Hasnayeen** [comment]
What's your filament version number?

**Comment by daab** [comment]
I made a new installation of Laravel with filament and it worked fine without error. In the project we are developing it gives the error. Keep investigating.
Mysteries give me life.
Thanks for your support.

Mingo.
