### ISSUE TITLE
[Bug]: Install package bugs

### ISSUE THREAD

**Issue by Thiktak** [Hasnayeen/themes#3]
### What happened?

Hello,

I have a serie of bug when installing this package on an existing installation.
Run upgrade/update, in order to use he last version if Laravel, filament & your package.

### pages/themes.blade.php

```@if ($this->getCurrentTheme() instanceof \Hasnayeen\Themes\Contracts\HasChangeableColor)```

GetCurrentTheme() is a class, but getCurrentTheme return a string (getName)

```php
    public function getCurrentTheme()
    {
        return app(\Hasnayeen\Themes\Themes::class)->getCurrentTheme(); //->getName();
    }
```

### Themes.php

For the function getCurrentThemeColor(), I had to modify like this:

```php
        if (Arr::has($this->getCurrentTheme()->getThemeColor(), $color)) {
            return ['primary' => Arr::get($this->getCurrentTheme()->getThemeColor(), $color)];
        } else {
            return $this->getCurrentTheme()->getPrimaryColor();
        }
```

The ['primary' => null] always exists. And Arr::get(Array, null) return the full array. Need to check existence with has (or use collect()->get(null, default)).

### Sunset Theme

Here I removed the Color:rgb in order to avoid ```Filament\Support\Colors\Color::rgb(): Argument #1 ($color) must be of type string, array given```. Maybe DefaultTheme too ?

```php
    public function getPrimaryColor(): array
    {
        return ['primary' => $this->getThemeColor()['blue']];
    }
```

### How to reproduce the bug

Follow installation notes.
Go to Themes, and play with options

### Package Version

v3.0.8

### PHP Version

8.2.4

### Laravel Version

v3.0.39

### Which operating systems does with happen with?

Windows

### Notes

(Thank you for this great package :) )

**Comment by Hasnayeen** [comment]
@Thiktak thanks for reporting the bug and hints, a fix has been deployed. If it's not fixed please reopen the issue. Thank you.
