### ISSUE TITLE
[Bug]: Duplicated right hand scrollbar

### ISSUE THREAD

**Issue by DariusIII** [Hasnayeen/themes#31]
### What happened?

After update to latest FilamentPHP version (3.1.23) themes started having a secondary scrollbar on right.

![image](https://github.com/Hasnayeen/themes/assets/3399658/7732140b-2ef5-48d5-b1ea-340e42f3bcd9)

This happens on resource edit page that has a relationmanager view below it. Both the relation manager and edit page have separate scrollbars. Every other page looks fine, even the resource manager view page. Issue happens only on edit page.

### How to reproduce the bug

Install latest version of this package and currently latest version of filament (3.1.23)

### Package Version

3.0.21

### Filament Version

3.1.23

### PHP Version

8.2.13

### Laravel Version

10.37.3

**Comment by DariusIII** [comment]
I am not sure, but only thing that could cause this might be this?

https://github.com/filamentphp/filament/pull/10290

**Comment by royalmediaco** [comment]
I'm not using this theme/package, but this scrollbar bug happens to me using filamentphp tables with bulk actions. It also started with the filamentphp 3.1.23 version. 

If I remove bulkActions(), the second scrollbar goes away. Bulk actions in 3.1.22 look fine.

**Comment by bmckay959** [comment]
@DariusIII can you try and add this class back by doing "inspect" in the browser to see if that fixes it?

**Comment by Hasnayeen** [comment]
this issues is fixed by https://github.com/filamentphp/filament/pull/10636
