### ISSUE TITLE
[Bug]: Theme Navigation item Duplication

### ISSUE THREAD

**Issue by JoshuaSigaban** [Hasnayeen/themes#47]
### What happened?

When Running the theme package on an application with Laravel Octane the Theme navigation item duplicates 

![Screenshot 2024-03-20 at 11 19 02](https://github.com/Hasnayeen/themes/assets/45688948/f17201dc-ec1a-4176-b6dc-1f0aab8d8c9b)

### How to reproduce the bug

Laravel App with Octane

### Package Version

^3.0

### Filament Version

^3.2.55

### PHP Version

^8.3

### Laravel Version

^10.48

**Comment by Hasnayeen** [comment]
Fixed by #51
