### ISSUE TITLE
[Bug]: Plugin not working when mode is user

### ISSUE THREAD

**Issue by michele-grifa** [Hasnayeen/themes#50]
### What happened?

Currently the plugin only works if is set to global mode.
If is set to user mode, the plugin correctly update the columns in the database for the user but the theme is not changed.

### How to reproduce the bug

- Follow the guide to enable per user theme
- Try to change theme or color
- The theme or color is not applied

### Package Version

3.0.22

### Filament Version

3.2.61

### PHP Version

8.1.25

### Laravel Version

10.48.4

**Comment by Hasnayeen** [comment]
have you added `SetTheme` middleware in the panel provider?

**Comment by michele-grifa** [comment]
Yes, i put it first, but the order doesn't change the behavior .

In another project that has tenancy, the problem is the same.

**Comment by Hasnayeen** [comment]
can't reproduce locally, can you try clearing config cache or check in SetTheme middleware line 48 if it returns correct theme after changing a theme

**Comment by michele-grifa** [comment]
Tomorrow i will try.

**Comment by michele-grifa** [comment]
I tried to config cache without success. At line 48 the theme is always the DefaultTheme.
If I put the middleware after all default Filament ones, it works.

**Comment by michele-grifa** [comment]
It works with tenancy too.

**Comment by Hasnayeen** [comment]
yes, the middleware have to come after the authenticate middleware otherwise there is no user yet when it is run
