### ISSUE TITLE
[Bug]: error Filament\Support\Colors\ColorManager::Filament\Support\Colors{closure}(): Argument #1 ($color) must be of type string, array given

### ISSUE THREAD

**Issue by craigvc** [Hasnayeen/themes#7]
### What happened?

Enabling Sunset them creates error Filament\Support\Colors\ColorManager::Filament\Support\Colors\{closure}(): Argument #1 ($color) must be of type string, array given

### How to reproduce the bug

Enable Sunset Theme

### Package Version

3.0.0

### PHP Version

8.2.0

### Laravel Version

10.0.0

### Notes

Filament\Support\Colors\ColorManager::Filament\Support\Colors\{closure}(): Argument #1 ($color) must be of type string, array given

**Comment by Hasnayeen** [comment]
please run `php artisan about` and tell the exact version of the package please

**Comment by NazarAli** [comment]
please update the filament
