### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zimamarrois** [Hasnayeen/themes#9]
### What happened?

Login Page Full On Sunset Theme

![image](https://github.com/Hasnayeen/themes/assets/98190592/b2ab8f93-1290-41aa-9cda-51de40d0f10c)

### How to reproduce the bug

?

### Package Version

3

### PHP Version

8.2

### Laravel Version

10

**Comment by Hasnayeen** [comment]
this issue been resolved by a1f1255
